Feature/add home total amount to deposit
fivetran/dbt_quickbooks_source pull request #53
Opened 2024-07-16 08:49 UTC by fivetran-avinash

**Please provide your name and company**

**Link the issue/feature request which this PR is meant to address**

**Detail what changes this PR introduces and how this addresses the issue/feature request linked above.**

**How did you validate the changes introduced within this PR?**

**Which warehouse did you use to develop these changes?**

**Did you update the CHANGELOG?**

- [ ] Yes

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)**

- [ ] Yes

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

**PR Template** 
- [Community Pull Request Template](?expand=1&template=pull_request_template.md) (default)

- [Maintainer Pull Request Template](?expand=1&template=maintainer_pull_request_template.md) (to be used by maintainers)

2024-07-17 19:54 UTC, fivetran-joemarkiewicz requested changes
This update looks good to me, I just have some documentation requests to be applied before approving. Let me know once this is ready for re-review. Thanks!

2024-07-17 19:54 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- Added the `home_total_amount` field into the  `stg_quickbooks__deposit` model to support the new multicurrency feature in the [v0.14.0 release of the `dbt_quickbooks` package](https://github.com/fi
```suggestion
- Added the `home_total_amount` field into the `stg_quickbooks__deposit` model to support the new multicurrency feature in the [v0.14.0 release of the `dbt_quickbooks` package](https://github.com/fivetran/dbt_quickbooks/releases/tag/v0.14.0).
```

2024-07-17 19:54 UTC, fivetran-joemarkiewicz commented on models/stg_quickbooks__deposit.sql
> +        home_total_amount,
Please be sure to add this to the [src](https://github.com/fivetran/dbt_quickbooks_source/blob/f9fb58596c28c395a4d45ac1e42fb0f3e2d694b6/models/src_quickbooks.yml#L363-L384) and [stg.yml](https://github.com/fivetran/dbt_quickbooks_source/blob/f9fb58596c28c395a4d45ac1e42fb0f3e2d694b6/models/stg_quickbooks.yml#L458-L487) files and regen the docs.

2024-07-17 19:54 UTC, fivetran-joemarkiewicz commented on models/stg_quickbooks__estimate.sql
> +        exchange_rate,
Please be sure to add this to the [src](https://github.com/fivetran/dbt_quickbooks_source/blob/f9fb58596c28c395a4d45ac1e42fb0f3e2d694b6/models/src_quickbooks.yml#L386-L411) and [stg.yml](https://github.com/fivetran/dbt_quickbooks_source/blob/f9fb58596c28c395a4d45ac1e42fb0f3e2d694b6/models/stg_quickbooks.yml#L489-L522) files and regen the docs.

2024-07-17 23:02 UTC, fivetran-avinash reviewed
@fivetran-joemarkiewicz Changes applied and docs regenerated, ready for re-review.

2024-07-18 20:57 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-07-19 19:35 UTC, fivetran-catfritz approved these changes
LGTM!

2024-07-22 16:52 UTC, merged